apiVersion: apps/v1
kind: Deployment
metadata:
  name: employee-management-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: employee-management
  template:
    metadata:
      labels:
        app: employee-management
    spec:
      containers:
        - name: app
          image: monika2508/employee-management-app
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: employee-management-service
spec:
  selector:
    app: employee-management
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
